language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs.
# See https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
#before_script: ./develop/get_test_data_all.bash

script: pytest
