{% set name = "brainload" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7d8adf073ac0620b4333e95d82c897a80ff0a9bc3c2bca8de5a50111adfa133d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - nibabel
    - numpy
    - pip
    - python
    - pytest
    - pytest-cov
    - pytest-runner
  run:
    - nibabel
    - numpy
    - python
    - pytest
    - pytest-cov
    - pytest-runner

test:
  imports:
    - brainload
  requires:
    - pytest
    - pytest-cov
    - pytest-runner

about:
  home: https://github.com/dfsp-spirit/brainload
  license: MIT
  license_family: MIT
  license_file: 
  summary: Load FreeSurfer brain imaging data with minimal cognitive load
  doc_url: http://dfsp-spirit.github.io/brainload 
  dev_url: https://github.com/dfsp-spirit/brainload

extra:
  recipe-maintainers:
    - dfsp-spirit
