package:
  name: brainload
  version: "0.1.1"

source:
  git_rev: v0.1.1
  git_url: https://github.com/dfsp-spirit/brainload.git

#source:
#  fn: brainload-0.1.1.tar.gz
#  md5: e347036acc50720c0903dc2221b2605d
#  url: https://pypi.python.org/packages/source/b/brainload/brainload-0.1.1.tar.gz

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - brainload

about:
  home: https://github.com/dfsp-spirit/brainload
  license: MIT
  license_file: LICENSE
