{% set name = "brainload" %}
{% set version = "0.3.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a5dbd8495f8c26232df7b4dc8fbd446cc910bf25489ea345fed1a18106ef5367

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  noarch: python

requirements:
  build:
    - python
  host:
    - nibabel
    - numpy
    - pip
    - python
    - pytest
    - pytest-runner
    - pytest-cov
  run:
    - nibabel
    - numpy
    - python {{ python }}
    - pytest
    - pytest-runner
    - pytest-cov

test:
  imports:
    - brainload
  requires:
    - pytest
    - pytest-runner
    - pytest-cov

about:
  home: https://github.com/dfsp-spirit/brainload
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Load FreeSurfer brain imaging data with minimal cognitive load.
  doc_url: http://dfsp-spirit.github.io/brainload
  dev_url: https://github.com/dfsp-spirit/brainload
  description: |
    Load FreeSurfer brain surface meshes and morphometry data files for single
    subjects and groups. This is a wrapper around nibabel that knows about the
    FreeSurfer directory structure. Also included are high-level functions
    typically required in the analysis of surface-based brain morphometry data.
    This included some command line tools, e.g., to perform quality checks on
    FreeSurfer data.

extra:
  recipe-maintainers:
    - dfsp-spirit
